### ISSUE TITLE
Sprint 2: Improvement - validate .yaml config file for create cluster

### ISSUE THREAD

**Issue by Magi-Jakimovska** [keitaroinc/enabler#21]
## Subtasks

- [x] check if necessary fields are present in .yaml config file
- [x] check if designated port in config file is free and print out a warning if not 
- [x] test on dif. environments
