### ISSUE TITLE
Sprint 2: Improvement - Extract istio config file as template

### ISSUE THREAD

**Issue by Magi-Jakimovska** [keitaroinc/enabler#25]
## Subtasks

- [x] Extract istio config file as template for grafana setting
- [x] Test on dif. environments

**Comment by Magi-Jakimovska** [comment]
## Subtask

- [x] test on dif. environments

**Comment by InaKeitaro** [comment]
PR related to this issue is:
- https://github.com/keitaroinc/devops-enabler/pull/44
